USE TinyDesk_SQL;
GO
/*----------------------
		TABLAS
------------------------*/
--CREACIÓN TABLA ÁREA
CREATE TABLE AREA 
(
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Nombre VARCHAR(30) NOT NULL UNIQUE
)
GO

--CREACIÓN TABLA ROL
CREATE TABLE ROL
(
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Nombre VARCHAR(30) NOT NULL UNIQUE,
	PermisoEscritura BIT NOT NULL
)
GO
--CREACIÓN TABLA USUARIO
CREATE TABLE USUARIO
(
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NombreUsuario VARCHAR(30) NOT NULL UNIQUE,
	PasswordHash VARCHAR(200) NOT NULL,
	Nombre VARCHAR(30) NOT NULL,
	Apellido VARCHAR(30) NOT NULL,
	Activo BIT NOT NULL DEFAULT 1,
	IdRol INT NOT NULL,
	IdArea INT NOT NULL,

	FOREIGN KEY (IdRol) REFERENCES ROL(Id),
	FOREIGN KEY (IdArea) REFERENCES AREA(Id)
)
GO

--CREACION TABLA ESTADO
CREATE TABLE ESTADO
(
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Nombre VARCHAR(30) NOT NULL UNIQUE
)
GO

--CREACION TABLA PRIORIDAD
CREATE TABLE PRIORIDAD
(
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Nombre VARCHAR(30) NOT NULL UNIQUE
)
GO

--CREACIÓN TABLA PROYECTO
CREATE TABLE PROYECTO
(
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Nombre VARCHAR(30) NOT NULL,
	Descripcion VARCHAR(250) NOT NULL,
	FechaInicio DATE NOT NULL,
	FechaFin DATE,
	Activo BIT NOT NULL DEFAULT 1,
	IdEstado INT NOT NULL,
	CHECK (FechaFin >= FechaInicio),
	
	FOREIGN KEY (IdEstado) REFERENCES ESTADO(Id)
)
GO

--CREACIÓN TABLA SPRINT
CREATE TABLE SPRINT
(
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	FechaInicio DATE NOT NULL,
	FechaFin DATE,
	IdProyecto INT NOT NULL,
	IdEstado INT NOT NULL,
	IdArea INT NOT NULL,

	CHECK (FechaFin >= FechaInicio),

	FOREIGN KEY (IdProyecto) REFERENCES PROYECTO(Id),
	FOREIGN KEY (IdEstado) REFERENCES ESTADO(Id),
	FOREIGN KEY (IdArea) REFERENCES AREA(Id)
)
GO

--CREACIÓN TABLA TICKET
CREATE TABLE TICKET
(
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	FechaInicio DATE NOT NULL,
	FechaFin DATE,
	Descripcion VARCHAR(150) NOT NULL,
	IdPrioridad INT NOT NULL,
	IdUsuario INT NOT NULL,
	IdEstado INT NOT NULL,
	IdSprint INT NOT NULL,

	CHECK(FechaFin >= FechaInicio),

	FOREIGN KEY (IdPrioridad) REFERENCES PRIORIDAD(Id),
	FOREIGN KEY (IdUsuario) REFERENCES USUARIO(Id),
	FOREIGN KEY (IdEstado) REFERENCES ESTADO(Id),
	FOREIGN KEY (IdSprint) REFERENCES SPRINT(Id)
)
GO

/*----------------------
		VISTAS
------------------------*/

