--CREACIÓN BASE DE DATOS
--create database TinyDesk_SQL
USE TinyDesk_SQL
GO
/*----------------------
		TABLAS
------------------------*/
--CREACIÓN TABLA ÁREA
CREATE TABLE AREA 
(
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Nombre VARCHAR(30) NOT NULL UNIQUE
)
GO

--CREACIÓN TABLA ROL
CREATE TABLE ROL
(
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Nombre VARCHAR(30) NOT NULL UNIQUE,
	PermisoEscritura BIT NOT NULL
)
GO
--CREACIÓN TABLA USUARIO
CREATE TABLE USUARIO
(
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NombreUsuario VARCHAR(30) NOT NULL UNIQUE,
	Pass VARCHAR(20) NOT NULL,
	Nombre VARCHAR(30) NOT NULL,
	Apellido VARCHAR(30) NOT NULL,
	Activo BIT NOT NULL,
	IdRol INT NOT NULL,
	IdArea INT NOT NULL,
	FOREIGN KEY (IdRol) REFERENCES ROL(Id),
	FOREIGN KEY (IdArea) REFERENCES AREA(Id)
)
GO

--CREACIÓN TABLA PROYECTO
CREATE TABLE PROYECTO
(
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Nombre VARCHAR(30) NOT NULL,
	Descripcion VARCHAR(250) NOT NULL,
	FechaInicio DATE CHECK(FechaInicio <= CAST(GETDATE() AS DATE)),
	FechaFin DATE CHECK(FechaFin >= FechaInicio),
	Activo BIT NOT NULL,
	IdEstado INT NOT NULL,
	FOREIGN KEY (IdEstado) REFERENCES ESTADO(Id)
)


--CREACIÓN TABLA SPRINT
CREATE TABLE 


--CREACIÓN TABLA TICKET
CREATE TABLE 



--CREACIÓN TABLA ESTADO
CREATE TABLE 




/*----------------------
		VISTAS
------------------------*/





